// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go

// Package daily is a generated GoMock package.
package daily

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// RetrieveBalanceByPeriod mocks base method.
func (m *MockRepository) RetrieveBalanceByPeriod(ctx context.Context, accountID int64, orgID string, initialDate, finalDate time.Time) ([]Balance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RetrieveBalanceByPeriod", ctx, accountID, orgID, initialDate, finalDate)
	ret0, _ := ret[0].([]Balance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RetrieveBalanceByPeriod indicates an expected call of RetrieveBalanceByPeriod.
func (mr *MockRepositoryMockRecorder) RetrieveBalanceByPeriod(ctx, accountID, orgID, initialDate, finalDate interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RetrieveBalanceByPeriod", reflect.TypeOf((*MockRepository)(nil).RetrieveBalanceByPeriod), ctx, accountID, orgID, initialDate, finalDate)
}

// RetrieveLastBalance mocks base method.
func (m *MockRepository) RetrieveLastBalance(ctx context.Context, accountID int64, orgID string) (Balance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RetrieveLastBalance", ctx, accountID, orgID)
	ret0, _ := ret[0].(Balance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RetrieveLastBalance indicates an expected call of RetrieveLastBalance.
func (mr *MockRepositoryMockRecorder) RetrieveLastBalance(ctx, accountID, orgID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RetrieveLastBalance", reflect.TypeOf((*MockRepository)(nil).RetrieveLastBalance), ctx, accountID, orgID)
}

// SaveNewBalance mocks base method.
func (m *MockRepository) SaveNewBalance(ctx context.Context, b Balance) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveNewBalance", ctx, b)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveNewBalance indicates an expected call of SaveNewBalance.
func (mr *MockRepositoryMockRecorder) SaveNewBalance(ctx, b interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveNewBalance", reflect.TypeOf((*MockRepository)(nil).SaveNewBalance), ctx, b)
}

// UpdateExistingBalance mocks base method.
func (m *MockRepository) UpdateExistingBalance(ctx context.Context, b Balance) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateExistingBalance", ctx, b)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateExistingBalance indicates an expected call of UpdateExistingBalance.
func (mr *MockRepositoryMockRecorder) UpdateExistingBalance(ctx, b interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateExistingBalance", reflect.TypeOf((*MockRepository)(nil).UpdateExistingBalance), ctx, b)
}
